### PR TITLE
Class enhancements

### PR DESCRIPTION
**Pull request by Vylantze**
Updated the spell lists of the community expansion classes. Added new infusions to Tinkerer (referencing the original source).

### CODE REVIEW

**Comment by ThyWoof** [comment]
I like the changes but you are touching 3 different classes from 3 different authors here. Might be easier if you consider a request per class. Discussed this with QA team and other developers and we pretty much agree on Tinkerer. Warlock and Witch are the ones still under discussion.

**Comment by ThyWoof** [comment]
Also keep in mind Witch author will finally be able to put time on this Class again. So it might be better to touch Witch later in the game. We are open for suggestions though.

**Comment by ThyWoof** [comment]
Feedback from @RealBazou : Basically, default/standard Witch spell list should add Dominate Monster, Feeblemind, and Weird.

**Comment by Vylantze** [comment]
Got it, I'll split the changes.

**Pull request closed without merging**
