### PR TITLE
 fix issues #1185 and #1166

### PR DESCRIPTION
**Pull request by DubhHerder**
took action to fix issues #1185  and #1166

### CODE REVIEW

**Comment by ThyWoof** [comment]
Thanks for the fixes but please revert back the sidecar changes. There is a good reason why both Monsters and Multiclass are sidecars. As soon as the monsters fixes are in the next nexus update will have the monsters DLL in the zip. If not enabled, like multiclass, it'll be fully isolated from the rest of CE. Monsters as it's own project will also give you the freedom to work on it independently as I do with Multiclass.

**Comment by DubhHerder** [comment]
Sidecar is too unstable and unreliable , it was accidentally forgotten from the last three releases. Nobody else uses them and I have heard of no good or valid reasons to put this code in a sidecar. This code is finished and complete and does not require constant tweaking like multiclass does. It's not comparable to multiclass, is comparable to feats or spells which remain pay of the primary dll

**Comment by ThyWoof** [comment]
I’m not aware about any instabilities in sidecar code. Nexus releases and builds are separate topics. It wasn’t on Nexus waiting for these fixes. I’ll merge and have the DLL back on next Nexus release once sidecar changes get reversed.

**Comment by DubhHerder** [comment]
> I’m not aware about any instabilities in sidecar code. Nexus releases and builds are separate topics. It wasn’t on Nexus waiting for these fixes. I’ll merge and have the DLL back on next Nexus release once sidecar changes get reversed.

I assumed it was a mistake because I didn't think anyone would remove content without notice. That's a very poor way to handle a community mod.  You mean you purposely removed content without informing any other contributors or users or including the change in the change log?

Why was this the only content removed when a bug was reported, when there have been dozens of other bug reports for other features/codes that have not been removed? 

If content is removed when waiting on fix, warlock should be removed. This does not look like fair treatment.

**Comment by ThyWoof** [comment]
this code throws lots of warnings reason why. merged your files under the sidecar.

**Pull request closed without merging**
